In [1]:
import numpy as np

In [31]:
def binary_cross_entropy(Y_true, Y_pred):
    return -np.sum(Y_true * np.log(Y_pred) + (1 - Y_true) * np.log(1 - Y_pred)) / Y_true.size

In [32]:
def calc_weights(y):
    n_ones = np.sum(y)
    n_total = y.shape[1]**2
    w_ones = 1 - n_ones / n_total
    w_zeros = 1 - w_ones
    w = y * (w_ones - w_zeros) + w_zeros
    return w

In [33]:
Y = np.zeros((10, 10))
Y[0,0] = 1
Y[0, 1] = 1
Y[0, 2] = 1
Y_true = Y[:]
Y_pred = Y * 0 + 0.0000001
Y_w = calc_weights(Y_true)

In [41]:
Y_true = Y[:]
Y_pred = Y * 0 + 0.001
Y_pred2 = Y * 0.5 + 0.001

In [42]:
print(Y_true)
print(Y_pred)
print(Y_pred2)

[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001]
 [ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001]
 [ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001]
 [ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001]
 [ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001]
 [ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001]
 [ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001]
 [ 0.001  0.001  0.001  0.001  0.001  0.001  0.001  0.001 

In [44]:
print(binary_cross_entropy(Y_true, Y_pred))
print(binary_cross_entropy(Y_w, Y_pred))
print(binary_cross_entropy(Y_true, Y_pred2))
print(binary_cross_entropy(Y_w, Y_pred2))

0.208203143693
0.402973628451
0.0217049606605
0.222695124724
