In [74]:
from keras import backend as K
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix

In [3]:
y_true_np = np.array([[1, 0, 0],
                      [1, 0, 0],
                      [0, 0, 1]])
y_pred_np = np.array([[0.6, 0.1, 0.2],
                      [0.4, 0.2, 0.3],
                      [0.1, 0.2, 0.3]])
y_true = K.variable(value=y_true_np)
y_pred = K.variable(value=y_pred_np)

In [4]:
# MAE on ones only
K.eval(K.sum(y_true - y_true * y_pred) / K.sum(y_true))

0.56666666

In [5]:
# MAE on zeros only
K.eval(K.sum((1 - y_true) * y_pred ) / K.sum(1 - y_true))

0.18333334

In [6]:
K.eval(K.equal(y_true, K.round(y_pred)))

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]], dtype=bool)

In [7]:
# accuracy
K.eval(K.mean(K.equal(y_true, K.round(y_pred))))

0.77777779

In [8]:
# accuracy on ones
K.eval(K.sum(K.round(y_true * y_pred)) / K.sum(y_true))


0.33333334

In [9]:
nom = K.sum(K.round(y_true * y_pred))
den = K.sum(y_true)
K.eval(nom / den)

0.33333334

In [10]:
# accuracy on zeros
den = 1 - y_true
nom = (1 - y_pred) * den
nom = K.round(nom)
den = K.sum(den)
nom = K.sum(nom)
print(K.eval(nom / den))
#K.eval(K.sum(1 - (1 - y_true) * K.round(y_pred)) / K.sum(1 - y_true))
#K.eval(K.sum(K.round(y_true * y_pred)) / K.sum(y_true))

1.0


In [11]:
print(K.eval(y_true))
print(K.eval(y_pred))

[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
[[ 0.60000002  0.1         0.2       ]
 [ 0.40000001  0.2         0.30000001]
 [ 0.1         0.2         0.30000001]]


In [12]:
K.eval(K.sum(K.round(1 - (1 - y_true) * y_pred) * (1 - y_true)) / K.sum(1 - y_true))

1.0

In [13]:
K.eval(y_pred)

array([[ 0.60000002,  0.1       ,  0.2       ],
       [ 0.40000001,  0.2       ,  0.30000001],
       [ 0.1       ,  0.2       ,  0.30000001]], dtype=float32)

In [14]:
yt = 1 - y_true
yp = 1 - y_pred

In [15]:
def metrics_acc_ones(y_true, y_pred):
    return K.sum(K.round(y_true * y_pred)) / K.sum(y_true)

In [16]:
K.eval(metrics_acc_ones(yt, yp))

1.0

In [17]:
def mae_zeros(y_true, y_pred):
    return K.sum((1 - y_true) * y_pred ) / K.sum(1 - y_true)

def mae_ones(y_true, y_pred):
    return K.sum(y_true - (y_true * y_pred)) / K.sum(y_true)

def acc_ones(y_true, y_pred):
    return K.eval(K.sum(K.round(y_true * y_pred)) / K.sum(y_true))

def acc_zeros(y_true, y_pred):
    den = 1 - y_true
    nom = (1 - y_pred) * den
    nom = K.round(nom)
    den = K.sum(den)
    nom = K.sum(nom)
    return nom / den

def acc_custom(y_true, y_pred):
    return K.mean(K.equal(y_true, K.round(y_pred)))

In [18]:
y_true_np = np.array([[1, 0, 0, 0],
                      [1, 0, 0, 1],
                      [0, 0, 0, 1],
                      [0, 0, 0, 0]])
y_pred_np = np.array([[0.6, 0.1, 0.2, 0.5],
                      [0.4, 0.2, 0.3, 0.7],
                      [0.1, 0.2, 0.3, 0.4],
                      [0.1, 0.2, 0.3, 0.8]])
y_true = K.variable(value=y_true_np)
y_pred = K.variable(value=y_pred_np)

In [19]:
mea_zeros_np = np.sum((0.1, 0.2, 0.5, 0.2, 0.3, 0.1, 0.2, 0.3, 0.1, 0.2, 0.3, 0.8)) / 12
mae_zeros_tf = K.eval(mae_zeros(y_true, y_pred))
print(mea_zeros_np, mae_zeros_tf)
assert abs(mea_zeros_np - mae_zeros_tf) < 1e-7

0.275 0.275


In [20]:
mae_ones_np = np.sum((1 - 0.6, 1 - 0.4, 1 - 0.7, 1 - 0.4)) / 4
mae_ones_tf = K.eval(mae_ones(y_true, y_pred))
print(mae_ones_np, mae_ones_tf)
assert abs(mae_ones_np - mae_ones_tf) < 1e-7

0.475 0.475


In [21]:
acc_ones_np = np.sum((1, 0, 0, 1)) / 4
acc_ones_tf = acc_ones(y_true, y_pred)
print(acc_ones_np, acc_ones_tf)
assert abs(acc_ones_np - acc_ones_tf) < 1e-7

0.5 0.5


In [22]:
acc_zeros_np = np.sum((1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0)) / 12
acc_zeros_tf = K.eval(acc_zeros(y_true, y_pred))
print(acc_zeros_np, acc_zeros_tf)
assert abs(acc_zeros_np - acc_zeros_tf) < 1e-7

0.833333333333 0.833333


In [23]:
acc_custom_np = np.sum((1, 1, 1, 1,
                        0, 1, 1, 1,
                        1, 1, 1, 0,
                        1, 1, 1, 0)) / 16
acc_custom_tf = K.eval(acc_custom(y_true, y_pred))
print(acc_custom_np, acc_custom_tf)
assert abs(acc_custom_np - acc_custom_tf) < 1e-7

0.8125 0.8125


In [24]:
print(K.eval(K.round(y_pred)))
print(K.eval(y_true))

[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]


In [25]:
# true positives
print(K.eval(K.round(y_pred)))

[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]]


In [47]:
# true negatives
y_pred_round = K.round(y_pred)
print("Y_true\n", K.eval(y_true))
print("Y_round\n", K.eval(y_pred_round))
print("Y_pred\n", K.eval(y_pred))

Y_true
 [[ 1.  0.  0.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]
Y_round
 [[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
Y_pred
 [[ 0.60000002  0.1         0.2         0.5       ]
 [ 0.40000001  0.2         0.30000001  0.69999999]
 [ 0.1         0.2         0.30000001  0.40000001]
 [ 0.1         0.2         0.30000001  0.80000001]]


In [70]:
K.eval(tf.size(y_true))

16

In [115]:
def true_positives(y_true, y_pred):
    y_tp = tf.logical_and(y_true > 0,y_pred > 0)
    y_tp = tf.reduce_sum(tf.cast(y_tp, tf.float32))
    return y_tp / tf.cast(tf.size(y_true), tf.float32)
def true_negatives(y_true, y_pred):
    y_tn = tf.logical_and(y_true < 1,y_pred < 1)
    y_tn = tf.reduce_sum(tf.cast(y_tn, tf.float32))
    return y_tn / tf.cast(tf.size(y_true), tf.float32)
def false_positives(y_true, y_pred):
    y_fp = tf.logical_and(y_true < 1,y_pred > 0)
    y_fp = tf.reduce_sum(tf.cast(y_fp, tf.float32))
    return y_fp / tf.cast(tf.size(y_true), tf.float32)
def false_negatives(y_true, y_pred):
    y_fn = tf.logical_and(y_true > 0,y_pred < 1)
    y_fn = tf.reduce_sum(tf.cast(y_fn, tf.float32))
    return y_fn / tf.cast(tf.size(y_true), tf.float32)

In [113]:
K.eval(true_positives(y_true, y_pred))

0.25220001

In [98]:
# TP
y_tp = tf.logical_and(y_true > 0,y_pred > 0)
y_tp = tf.reduce_sum(tf.cast(y_tp, tf.float32))
K.eval(y_tp / tf.cast(tf.size(y_true), tf.float32))
# K.eval(tf.size(y_true))

0.25220001

In [53]:
# TN
y_tn = tf.logical_and(y_true < 1,y_pred_round < 1)
y_tn = tf.reduce_sum(tf.cast(y_tn, tf.float32))
K.eval(y_tn)

11.0

In [54]:
# FP
y_fp = tf.logical_and(y_true < 1,y_pred_round > 0)
y_fp = tf.reduce_sum(tf.cast(y_fp, tf.float32))
K.eval(y_fp)

1.0

In [55]:
# FN
y_fn = tf.logical_and(y_true > 0,y_pred_round < 1)
y_fn = tf.reduce_sum(tf.cast(y_fn, tf.float32))
K.eval(y_fn)

2.0

In [42]:
K.eval(y_true > 0)

array([[ True, False, False, False],
       [ True, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False]], dtype=bool)

In [ ]:
y_true_np = np.random
y_pred_np = np.array([[0.6, 0.1, 0.2],
                      [0.4, 0.2, 0.3],
                      [0.1, 0.2, 0.3]])
y_true = K.variable(value=y_true_np)
y_pred = K.variable(value=y_pred_np)

In [82]:
y_true_np = np.around(np.random.random((100, 100)))
y_pred_np = np.around(np.random.random((100, 100)))
y_true = K.variable(value=y_true_np)
y_pred = K.variable(value=y_pred_np)

In [83]:
tn, fp, fn, tp = confusion_matrix(y_true_np.flatten(), y_pred_np.flatten()).ravel()
s = tn + fp + fn + tp
print("TN: ", tn/s)
print("TP: ", tp/s)
print("FN: ", fn/s)
print("FP: ", fp/s)

TN:  0.2458
TP:  0.2522
FN:  0.2516
FP:  0.2504


In [119]:
print("TN: ", K.eval(true_negatives(y_true, y_pred)))
print("TP: ", K.eval(true_positives(y_true, y_pred)))
print("FN: ", K.eval(false_negatives(y_true, y_pred)))
print("FP: ", K.eval(false_positives(y_true, y_pred)))

TN:  0.2458
TP:  0.2522
FN:  0.2516
FP:  0.2504
