In [ ]:
from keras import backend as K
import numpy as np

In [41]:
y_true_np = np.array([[1, 0, 0],
                      [1, 0, 0],
                      [0, 0, 1]])
y_pred_np = np.array([[0.6, 0.1, 0.2],
                      [0.4, 0.2, 0.3],
                      [0.1, 0.2, 0.3]])
y_true = K.variable(value=y_true_np)
y_pred = K.variable(value=y_pred_np)

In [5]:
# MAE on ones only
K.eval(K.sum(y_true - y_true * y_pred) / K.sum(y_true))

0.56666666

In [6]:
# MAE on zeros only
K.eval(K.sum((1 - y_true) * y_pred ) / K.sum(1 - y_true))

0.18333334

In [61]:
K.eval(K.equal(y_true, K.round(y_pred)))

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]], dtype=bool)

In [7]:
# accuracy
K.eval(K.mean(K.equal(y_true, K.round(y_pred))))

0.77777779

In [28]:
# accuracy on ones
K.eval(K.sum(K.round(y_true * y_pred)) / K.sum(y_true))


0.33333334

In [71]:
nom = K.sum(K.round(y_true * y_pred))
den = K.sum(y_true)
K.eval(nom / den)

0.33333334

In [82]:
# accuracy on zeros
den = 1 - y_true
nom = (1 - y_pred) * den
nom = K.round(nom)
den = K.sum(den)
nom = K.sum(nom)
print(K.eval(nom / den))
#K.eval(K.sum(1 - (1 - y_true) * K.round(y_pred)) / K.sum(1 - y_true))
#K.eval(K.sum(K.round(y_true * y_pred)) / K.sum(y_true))

1.0


In [43]:
print(K.eval(y_true))
print(K.eval(y_pred))

[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
[[ 0.60000002  0.1         0.2       ]
 [ 0.40000001  0.2         0.30000001]
 [ 0.1         0.2         0.30000001]]


In [54]:
K.eval(K.sum(K.round(1 - (1 - y_true) * y_pred) * (1 - y_true)) / K.sum(1 - y_true))

1.0

In [55]:
K.eval(y_pred)

array([[ 0.60000002,  0.1       ,  0.2       ],
       [ 0.40000001,  0.2       ,  0.30000001],
       [ 0.1       ,  0.2       ,  0.30000001]], dtype=float32)

In [56]:
yt = 1 - y_true
yp = 1 - y_pred

In [59]:
def metrics_acc_ones(y_true, y_pred):
    return K.sum(K.round(y_true * y_pred)) / K.sum(y_true)

In [60]:
K.eval(metrics_acc_ones(yt, yp))

1.0

In [102]:
def mae_zeros(y_true, y_pred):
    return K.sum((1 - y_true) * y_pred ) / K.sum(1 - y_true)

def mae_ones(y_true, y_pred):
    return K.sum(y_true - (y_true * y_pred)) / K.sum(y_true)

def acc_ones(y_true, y_pred):
    return K.eval(K.sum(K.round(y_true * y_pred)) / K.sum(y_true))

def acc_zeros(y_true, y_pred):
    den = 1 - y_true
    nom = (1 - y_pred) * den
    nom = K.round(nom)
    den = K.sum(den)
    nom = K.sum(nom)
    return nom / den

def acc_custom(y_true, y_pred):
    return K.mean(K.equal(y_true, K.round(y_pred)))

In [108]:
y_true_np = np.array([[1, 0, 0, 0],
                      [1, 0, 0, 1],
                      [0, 0, 0, 1],
                      [0, 0, 0, 0]])
y_pred_np = np.array([[0.6, 0.1, 0.2, 0.5],
                      [0.4, 0.2, 0.3, 0.7],
                      [0.1, 0.2, 0.3, 0.4],
                      [0.1, 0.2, 0.3, 0.8]])
y_true = K.variable(value=y_true_np)
y_pred = K.variable(value=y_pred_np)

In [119]:
mea_zeros_np = np.sum((0.1, 0.2, 0.5, 0.2, 0.3, 0.1, 0.2, 0.3, 0.1, 0.2, 0.3, 0.8)) / 12
mae_zeros_tf = K.eval(mae_zeros(y_true, y_pred))
print(mea_zeros_np, mae_zeros_tf)
assert abs(mea_zeros_np - mae_zeros_tf) < 1e-7

0.275 0.275


In [127]:
mae_ones_np = np.sum((1 - 0.6, 1 - 0.4, 1 - 0.7, 1 - 0.4)) / 4
mae_ones_tf = K.eval(mae_ones(y_true, y_pred))
print(mae_ones_np, mae_ones_tf)
assert abs(mae_ones_np - mae_ones_tf) < 1e-7

0.475 0.475


In [121]:
acc_ones_np = np.sum((1, 0, 0, 1)) / 4
acc_ones_tf = acc_ones(y_true, y_pred)
print(acc_ones_np, acc_ones_tf)
assert abs(acc_ones_np - acc_ones_tf) < 1e-7

0.5 0.5


In [124]:
acc_zeros_np = np.sum((1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0)) / 12
acc_zeros_tf = K.eval(acc_zeros(y_true, y_pred))
print(acc_zeros_np, acc_zeros_tf)
assert abs(acc_zeros_np - acc_zeros_tf) < 1e-7

0.833333333333 0.833333


In [123]:
acc_custom_np = np.sum((1, 1, 1, 1,
                        0, 1, 1, 1,
                        1, 1, 1, 0,
                        1, 1, 1, 0)) / 16
acc_custom_tf = K.eval(acc_custom(y_true, y_pred))
print(acc_custom_np, acc_custom_tf)
assert abs(acc_custom_np - acc_custom_tf) < 1e-7

0.8125 0.8125


In [134]:
print(K.eval(K.round(y_pred)))
print(K.eval(y_true))

[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]


In [133]:
# true positives
print(K.eval(K.round(y_pred)))

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]], dtype=float32)

In [129]:
# true negatives

In [130]:
# false negatives

In [131]:
# false positives